#!/bin/bash

scriptdir=$(dirname $0)
scriptname=$(basename $0)

cd ${scriptdir}

if cmd=$(PYTHON=. python ${scriptdir}/${scriptname}.py "$@"); then {
    echo ${cmd}
    ${cmd}
} else {
    echo ${cmd}
} fi
